### ISSUE TITLE
Name Change Error

### ISSUE THREAD

**Issue by SwizzyStudios** [byt3m/Valheim-Character-Editor#1]
Tried to change my name to BDR from VEV got this error, also when I left the name as VEV it still didn't like it.

![image](https://user-images.githubusercontent.com/46543438/107889973-c102a000-6edb-11eb-957f-c8eaae8db27c.png)

**Comment by SwizzyStudios** [comment]
https://github.com/byt3m/Valheim-Character-Editor/blob/7ef723814ecaa6021ab3e429cf5f773e59fd47b2/ValheimCharacterEditor/Customization.cs#L357

making it inclusive should fix it

**Comment by byt3m** [comment]
I modified it to allow from 3 characters to 15. Let me know if it works now.

**Comment by SwizzyStudios** [comment]
looks good
