### ISSUE TITLE
request: copy map exploration between servers

### ISSUE THREAD

**Issue by taleden** [byt3m/Valheim-Character-Editor#10]
This seems a bit outside the scope of your project right now, but it's the only one I know of that's doing anything with decoding the .fch file format, so I'll toss the idea in here anyway:

It would be really neat if it were possible to copy the data related to a character's revealed areas of the map on one server to apply to a different server (along with, I guess, any other server-specific data that's stored in the character file, but this is the most obvious example).

The reason someone might want to do this is when a world is transferred from one server host to another (such as, in our case, starting with one player hosting themselves, and then moving to a dedicated server). Even though it's the same world file with the same name, seed, etc, the client sees it as different because of (I assume) the server address, which means the map is reset to having nothing explored, no map makers, etc.

**Comment by byt3m** [comment]
I assume you moved the world .DB and .FWL files to the dedicated server? If so, then the exploration data is more likely to be held in the character .FCH as you pointed. I will add this as a possible feature in the future, but, I cannot make any promises.
