### ISSUE TITLE
Running on linux with mono but don't recognize path to game folder.

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [byt3m/Valheim-Character-Editor#11]
Hi!

So I managed to run the edito on linux via mono, basically "mono ValheimCharacterEditor.exe", it runs fine, but it doesn't recognize the file system tree, since you know window$ is c:\ and linux is /
Could you get around that? Since Valheim is a linux native game, developed on linux, it would be awesome to have this working also, then I could make a little text howto-trouble shoot on how to get it to run on linux, basically just installing mono-complete for linux.
Let me know if you want a screenshot of the character editor, it shows the disc system tree as it was on window$.

Thank you for your time!

**Comment by byt3m** [comment]
I dont know how to program it to automatically detect your .FCH files on Linux, but I could compile a version with the path "hardcoded" for linux if you tell me exactly the path where character files are held in your OS.

**Comment by WaldoTheRanger** [comment]
Also on linux (manjaro) and it runs fine with wine
When I started it, when it said "can't find folder", it popped up with a window that had my desktop selected by default
So I guess I'd try wine instead.

**Comment by byt3m** [comment]
Let me know if it works with wine.

**Comment by WaldoTheRanger** [comment]
I meant it definitely does work. I was just recommending it to the Op.
