### ISSUE TITLE
Name not changed for beds

### ISSUE THREAD

**Issue by Frazzer951** [byt3m/Valheim-Character-Editor#14]
The characters name changed, but when a bed is claimed, it still shows the old name

**Comment by FakeMichau** [comment]
Not much can be done about that, that data is stored in the world file. 
Can it still be used?

**Comment by Frazzer951** [comment]
Even when I switch beds it keeps the old name, I would think it would be a character-related thing, but if not, it's fine.

**Comment by FakeMichau** [comment]
Try changing name of the characterName.fch file in C:\Users\USERNAME\AppData\LocalLow\IronGate\Valheim\characters
There's a small chance that it takes file name for some reason. If this doesn't work then the world file probably holds some kind of cache with all the names. I haven't looked into that file yet so i'm not 100% sure.

**Comment by Frazzer951** [comment]
The program changes the file name already

**Comment by FakeMichau** [comment]
The only thing I see potentially working would be to resetting/changing character's id. Sadly this would result in losing access to already existing beds and wards.

**Comment by byt3m** [comment]
Did you test if the bed works? I mean, killing yourself and spawning on it.

**Comment by Frazzer951** [comment]
Yes, you do spawn at the bed still

**Comment by FakeMichau** [comment]
We could add an option to change character id with a disclaimer that the already exising beds/wards won't work. I've tested it and it works. Don't know about any other potential side effects.
Sadly this game is quite basic in the implementation of many features. 20MB character files are one of those things.

**Comment by byt3m** [comment]
If the bed keeps working without problem I think theres no need to change anything as long as it does not give problems.
