### ISSUE TITLE
Error while applying the new customization

### ISSUE THREAD

**Issue by NordikaMan** [byt3m/Valheim-Character-Editor#2]
![image](https://user-images.githubusercontent.com/9384449/107890660-f5239400-6ece-11eb-8498-805010aae4f2.png)

I get this error each time I try and apply any changes to my character.

**Comment by byt3m** [comment]
Seems like your current character has a weird letter in his name. I will try to reproduce this tomorrow and check it.

**Comment by NordikaMan** [comment]
Awesome, thanks!

**Comment by byt3m** [comment]
I did some fixes, can you check if its working now?

**Comment by NordikaMan** [comment]
Works now! Thank you very much!

(did get the naked on first login bug but logging out and back in fixed it)

**Comment by NordikaMan** [comment]
Seems to have reset many of my skills back to 0 though, unfortunately.

**Comment by byt3m** [comment]
I am away of this issue, there is more people having the same problem. For some reason this only happens with some names, maybe because of weird characters I dont know. If you want you can send me your .FCH before changing the name and tell me which name exactly did you changed it to.

**Comment by NordikaMan** [comment]
Of course! Here's the original character file: 

[bjørn.fch.txt](https://github.com/byt3m/Valheim-Character-Editor/files/5983794/bjorn.fch.txt)

(remove .txt obviously; GitHub doesn't like .fch files)

I tried renaming to NORDIKAMAN with Long 1 hair, Long 1 beard and Blonde color choice.

**Comment by byt3m** [comment]
Nice thanks! I will start analyzing it.

**Comment by NordikaMan** [comment]
The customization changes worked! But a handful of skills were reset to 0 was the issue.

Did that not happen for you?

**Comment by byt3m** [comment]
No, it seems to happen only for some people. This happens because the game rewrites some part of the FCH file for some reason. I am glad it works now for you, even after losing your skills. I am sorry for that.
