### ISSUE TITLE
Character Gender modification

### ISSUE THREAD

**Issue by blandman** [byt3m/Valheim-Character-Editor#21]
I've been wanting to change my Valheim character's gender, and found this awesome tool.

I dug through the code, got a version running locally that changes Gender via checkbox, was really happy and proud for the chance to contribute, then when I went and made a PR, I noticed the new parser. PR just couldn't happen at that point.

It's late and I'm not understanding how the new parser works, but here's my findings on changing gender.

it's a single byte, 00 = male, 01 = female, and the byte is +24 bytes from the last checked hair color in the old parser.

```
42 65 61 72 64 4E 6F 6E 65 05 48 61 69 72 33 66 66 26 3F 66 66 26 3F 66 66 26 3F 39 F7 D9 3D 00 EF CA 3D AF DB 99 3D 01
BeardNoneHair3ff&?ff&?ff&?9÷Ù=�ïÊ=¯Û™=
```

Last 01 byte there indicates gender.

**Comment by FakeMichau** [comment]
Awesome work! Changing gender wasn't yet made available in gui but if you dig into the code a little you can change every value that the save stores, including gender, thanks to the new parser. My pr wasn't yet merged so gender should still be called "model". 
If you want to contribute then look at the v1.5 branch.

**Comment by blandman** [comment]
Ahha, awesome thank you so much. I did see model in the place where I expected gender, this makes a lot of sense. I really appreciate it <3
