### ISSUE TITLE
Character cannot be found 

### ISSUE THREAD

**Issue by Edibieee** [byt3m/Valheim-Character-Editor#3]
I've been playing this game for more than 22 hours already but when I launched the app, it says that it can't find my character. 
[https://i.ibb.co/Jx5CvFQ/Capture.jpg](url)

**Comment by byt3m** [comment]
This is probably happening because the program cant find the .FCH file associated to your character. Can you check that your character files are under "C:\Users<username>\AppData\LocalLow\IronGate\Valheim\characters" and provide me with a screenshot?

**Comment by Yuri909** [comment]
So my name has a space in it and it can't be found either. The file is titled "Yur i.fch" and the launcher says it can't find a character haha... it's in the folder where it belongs. I'm trying to take the stupid space out of the name lmao. Got to dozens of levels across several skills before we noticed it.

**Comment by byt3m** [comment]
Did you chose that name with a space in-game or was it with my program? If you want to fix your .FCH file download "HxD" and just change the first name you encounter in the file. This should fix it.

**Comment by nhwalton** [comment]
Running into the same issue with characters with a space in the name. Both characters I've created have spaces, both show up in the list, both give the same error that @Edibieee sent a screenshot of. The .fch files in the characters directory have a space in the names.

**Comment by Edibieee** [comment]
> This is probably happening because the program cant find the .FCH file associated to your character. Can you check that your character files are under "C:\Users\[username]\AppData\LocalLow\IronGate\Valheim\characters" and provide me with a screenshot?

Yes, it's in the folder. https://i.ibb.co/yXkx26s/Tita-B.jpg

**Comment by Yuri909** [comment]
> Did you chose that name with a space in-game or was it with my program? If you want to fix your .FCH file download "HxD" and just change the first name you encounter in the file. This should fix it.

Like I said, it was in game by accident. No idea how it happened. The editor refuses to see the file as actually there even though it detects the name.

**Comment by byt3m** [comment]
Yes a lot of people are having the same problems, I will investigate it now that some of them sent me their .FCH files.

**Comment by nhwalton** [comment]
@byt3m confirming v1.3 fixed this issue for me. Cheers!
