### ISSUE TITLE
Advanced edit character model

### ISSUE THREAD

**Issue by pedrohenriquebr** [byt3m/Valheim-Character-Editor#33]
I would like to edit my character skin like minecraft skin editors.

**Comment by FakeMichau** [comment]
The only things the game allows are:
- change character model (aka gender)
- change hair color (by editing save file you can edit rgb values)
- change skin color (same as hair but color intensity controls how white or brown the skin is, so some colors look weird)
- change beard model
- change hair model

You can see that at line 147 of the Parser.cs.
If you want more customization then you would have to suggest such thing to the game developer.

**Comment by pedrohenriquebr** [comment]
My thought was a patching the character 3D model.
