### ISSUE TITLE
Editing skin color

### ISSUE THREAD

**Issue by ArcadeMode** [byt3m/Valheim-Character-Editor#4]
Hey there!

Cool project, I am wondering when support for editing skin color will be ready?
I would like to help out with implementing such a feature, if you could give me some pointers on the layout of the character file and the way you are manipulating it.

Looking forward to hearing from you!

Edit: rephrasing
Edit2: typo

**Comment by byt3m** [comment]
I will keep updating the program as soon as I have some spare time. Also I will pm you if I need help in the future :).
