### ISSUE TITLE
Offering a hand

### ISSUE THREAD

**Issue by Mixone-FinallyHere** [byt3m/Valheim-Character-Editor#5]
Hey!

Awesome work!

I have a few other ideas and am very comfortable with C#, was going to make a fork and then pr but my main idea would pretty much change the whole structure so I'd rather maybe discuss it with you first?

Not sure how to contact you but I am on discord, I can message you what I was thinking off.

Amongst the ideas:

- New character creator: Fairly simple since the bytedata required structure is know.
- Inventory editor: You are already working on this but had some input
- More robust codebase: Character class itself for example to make code more readably modifiable for the future.

**Comment by byt3m** [comment]
Hi, I am thinking about doing some changes, like moving the logic to C++ as it is a lot easier for these type of things (editing file by bytes) and much more efficient. How much skilled are you in C++?

**Comment by Mixone-FinallyHere** [comment]
Hmmm c++ I am nowhere near as "comfortable" with I think

**Comment by byt3m** [comment]
Anyway that is not likely to happen atm. If you want to contribute maybe you could find other values in the .FCH file. Like character skin color, gender, etc.
