### ISSUE TITLE
"Name not found for character..."

### ISSUE THREAD

**Issue by BaSS9380** [byt3m/Valheim-Character-Editor#6]
I wanted just to change my name, but I didn't disable steam cloud on my first try. Now it says what's on the screenshot, logging onto the character doesn't help at all
![image](https://user-images.githubusercontent.com/79154326/108080714-75352f80-7070-11eb-9c08-d94ae631670f.png)

**Comment by byt3m** [comment]
Go to C:\Users\agd\AppData\LocalLow\IronGate\Valheim\characters and restore the last backup of your character (before changing name). I will add space support or just forbid them on my program because they are giving problems.
