### ISSUE TITLE
Limited Character Support

### ISSUE THREAD

**Issue by D3V3L0P3R22** [byt3m/Valheim-Character-Editor#7]
Program does not work with Characters named with special characters that are allowed by the game....
These are the one I am using causing the issue. 
ᴅѳᴩꝛꝚỉѵᴌᴣ
Otherwise Great App,
Thanks!!

**Comment by byt3m** [comment]
Hi, I plan on adding special character support if I find a way. Currently my program chooses characters by their file name and windows doesn't allow most of special characters on file names.
