### ISSUE TITLE
Hair not found, colour not found, pattern not found

### ISSUE THREAD

**Issue by McKay91** [byt3m/Valheim-Character-Editor#8]
![1](https://user-images.githubusercontent.com/79256795/108347528-8731e200-71d8-11eb-8620-0c3fee2d45a7.png)
![2](https://user-images.githubusercontent.com/79256795/108347530-8731e200-71d8-11eb-8fbb-02e5b0cf169a.png)
![3](https://user-images.githubusercontent.com/79256795/108347531-87ca7880-71d8-11eb-854f-d2ab94339c62.png)
[mckay.zip](https://github.com/byt3m/Valheim-Character-Editor/files/6002302/mckay.zip)

I've attached my character file

**Comment by byt3m** [comment]
Here you go, I fixed it. Did my program break it or was it a game bug?


[mckay.zip](https://github.com/byt3m/Valheim-Character-Editor/files/6005035/mckay.zip)

**Comment by 4hmedSamir** [comment]
I have the same bug, could you release the fix?

**Comment by probicassassin** [comment]
I am having the same issue :/
Pattern Not Found
Name not found for character dazed

[dazed.zip](https://github.com/byt3m/Valheim-Character-Editor/files/6014391/dazed.zip)

**Comment by busheezy** [comment]
I have the same issue. I think it is because I never changed anything in the game's character selection and left it the way it gave me.

**Comment by greenfeuer** [comment]
^ I have the same problem as all the above. - I haven´t found out how to send the zip/find the character save tho. - I change my character tho, but color, hair color, beard, and yeah, every slider actually. - So I don´t think its the preset/generic look that gives the bug out :(

**Comment by byt3m** [comment]
The next version will have an improved repair function. At the moment, you can send me your .FCH file and I check it manually. The path to .FCH files is described in the main github page.

**Comment by byt3m** [comment]
> 
> 
> I am having the same issue :/
> Pattern Not Found
> Name not found for character dazed
> 
> [dazed.zip](https://github.com/byt3m/Valheim-Character-Editor/files/6014391/dazed.zip)

When the games saves your character it usually makes the first letter capital, but in your case the name is just "dazed" inside the .FCH file. I will have to take this in mind for future versions. The rest of your character .FCH file is fine.

**Comment by greenfeuer** [comment]
[Skalp.zip](https://github.com/byt3m/Valheim-Character-Editor/files/6025100/Skalp.zip)
Found the file finally, gonna throw it here - Hope you can help me out and thanks for making this mod aswell :)

**Comment by greenfeuer** [comment]
[skalp.zip](https://github.com/byt3m/Valheim-Character-Editor/files/6026086/skalp.zip)
Managed to find the file needed! - Thanks for making this mod and hope you can help me out 🗡️ :D

**Comment by greenfeuer** [comment]
[skalp.zip](https://github.com/byt3m/Valheim-Character-Editor/files/6031592/skalp.zip)

-

Managed to find the file needed! - Thanks for making this mod and hope you can help me out 🗡️ :D - Had to update it, since I played abit since last time :)

**Comment by byt3m** [comment]
[skalp_fixed.zip](https://github.com/byt3m/Valheim-Character-Editor/files/6038049/skalp_fixed.zip)

There you go, the next version will solve all these problems.
